name: 'Setup'
inputs: 
  cloud:
    description: 'cloud'
runs:
  using: 'composite'
  steps:
      - name: ECS
        uses: rodrigocamposbr/teste/.github/actions/ecs@main
        if: ${{ endsWith(inputs.cloud, ':ecs') }}
          
      - name: LAMBDA
        uses: rodrigocamposbr/teste/.github/actions/lambda@main
        if: ${{ endsWith(inputs.cloud, ':lambda') }}
