name : demo
on:
    workflow_dispatch:
      inputs:
        cloud:
          type: string
          default: "aws:ecs"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: AWS
        if: ${{ startsWith(inputs.cloud, 'aws:') }}
        #if: ${{ endsWith(inputs.cloud, ':aws') }}
        uses: rodrigocamposbr/teste/@main
        with:
          cloud: ${{ inputs.cloud }}
