name: Exemplo de GitHub Action

on:
  workflow_dispatch:
    inputs:
      container:
        default: ubuntu:latest

jobs:
  exemplo-job:
    runs-on: ubuntu-latest
    container: 
      image: ${{ inputs.container }}

    steps:
    - name: Configurar ambiente
      run: echo "Configurando ambiente"

    - name: Obter valores do input
      run: |
        cat /etc/*-release
        date
        uname

  exemplo-2:
    runs-on: ubuntu-latest
    steps:
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
